---
include:
  - board: nice_nano
    shield: skeletyl_dongle
  - board: nice_nano
    shield: skeletyl_left
  - board: nice_nano
    shield: skeletyl_right
  - board: nice_nano
    shield: cygnus_left
  - board: nice_nano
    shield: cygnus_right
  - board: nice_nano
    shield: settings_reset 
