file_format: "1"
id: skeletyl
name: The skeletyl 
type: shield
url: https://github.com/stefanwatt/zmk-dongle
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - skeletyl_left
  - skeletyl_right
  - skeletyl_dongle
